#!/usr/bin/env node
import * as youtubeTranscript from "youtube-transcript-plus";

const input = process.argv[2];
const language = process.argv[3];

if (!input || input === "-h" || input === "--help") {
	console.error("Usage: transcript.js <video-id-or-url> [language]");
	console.error("Example: transcript.js EBw7gsDPAYQ");
	console.error("Example: transcript.js https://www.youtube.com/watch?v=EBw7gsDPAYQ");
	console.error("Example: transcript.js https://youtu.be/EBw7gsDPAYQ en");
	process.exit(input ? 0 : 1);
}

const fetchTranscript = youtubeTranscript.fetchTranscript ?? youtubeTranscript.YoutubeTranscript?.fetchTranscript;
const listLanguages = youtubeTranscript.listLanguages;

if (typeof fetchTranscript !== "function") {
	console.error("Error: youtube-transcript-plus did not expose fetchTranscript(). Try `npm install` in this skill directory.");
	process.exit(1);
}

try {
	const result = await fetchTranscript(input, {
		...(language ? { lang: language } : {}),
		retries: 2,
		retryDelay: 1000,
	});

	const segments = Array.isArray(result) ? result : result?.segments;
	if (!Array.isArray(segments) || segments.length === 0) {
		throw new Error("No transcript segments returned.");
	}

	for (const segment of segments) {
		const timestamp = formatTimestamp(segmentStartSeconds(segment));
		const text = normalizeText(segment.text);
		if (text) console.log(`[${timestamp}] ${text}`);
	}
} catch (error) {
	console.error("Error fetching transcript:", error?.message ?? String(error));

	if (language && Array.isArray(error?.availableLangs) && error.availableLangs.length > 0) {
		console.error(`Available languages: ${error.availableLangs.join(", ")}`);
	} else if (language && typeof listLanguages === "function") {
		try {
			const languages = await listLanguages(input);
			if (Array.isArray(languages) && languages.length > 0) {
				const formatted = languages
					.map((item) => `${item.languageCode}${item.isAutoGenerated ? " (auto)" : ""}`)
					.join(", ");
				console.error(`Available languages: ${formatted}`);
			}
		} catch {
			// Ignore secondary diagnostics failures.
		}
	}

	process.exit(1);
}

function segmentStartSeconds(segment) {
	const rawOffset = Number(segment.offset ?? segment.start ?? 0);
	const rawDuration = Number(segment.duration ?? 0);

	// youtube-transcript-plus currently reports seconds, while older/forked
	// transcript packages often reported milliseconds. Use duration as the
	// strongest unit signal and fall back to a conservative offset threshold.
	const looksLikeMilliseconds = rawDuration > 100 || rawOffset > 24 * 60 * 60;
	return looksLikeMilliseconds ? rawOffset / 1000 : rawOffset;
}

function formatTimestamp(totalSeconds) {
	const safeSeconds = Math.max(0, Math.floor(Number.isFinite(totalSeconds) ? totalSeconds : 0));
	const hours = Math.floor(safeSeconds / 3600);
	const minutes = Math.floor((safeSeconds % 3600) / 60);
	const seconds = safeSeconds % 60;

	if (hours > 0) {
		return `${hours}:${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`;
	}
	return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}

function normalizeText(value) {
	return decodeHtmlEntities(String(value ?? ""))
		.replace(/\s+/g, " ")
		.trim();
}

function decodeHtmlEntities(text) {
	const named = {
		amp: "&",
		lt: "<",
		gt: ">",
		quot: '"',
		apos: "'",
		nbsp: " ",
		ndash: "–",
		mdash: "—",
		hellip: "…",
	};

	return text.replace(/&(#x[\da-f]+|#\d+|[a-z][a-z0-9]+);/gi, (entity, body) => {
		if (body.startsWith("#x") || body.startsWith("#X")) {
			const codePoint = Number.parseInt(body.slice(2), 16);
			return Number.isFinite(codePoint) ? String.fromCodePoint(codePoint) : entity;
		}
		if (body.startsWith("#")) {
			const codePoint = Number.parseInt(body.slice(1), 10);
			return Number.isFinite(codePoint) ? String.fromCodePoint(codePoint) : entity;
		}
		return named[body.toLowerCase()] ?? entity;
	});
}
